language: python
python:
  - "3.7"

before_install:
  - pip install poetry==1.0.9
install:
  - poetry install

jobs:
  include:
    - stage: test
      name: "Formatting"
      script:
        - black --check .
        - isort --recursive --check-only
    - stage:
      name: "Linting"
      script:
        - flake8
    - stage:
      name: "Testing"
      script:
        - pytest
